stages:
  - deploy

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: fetch

update_sourcecodes_staging:
  stage: deploy
  tags:
    - staging-stbip-u1
  script:
    - echo "Updating codebase and deploying containers"
    - cd "$PROJECT_DIRECTORY"
    - git stash
    - git fetch
    - git switch $CI_COMMIT_BRANCH
    - git pull origin $CI_COMMIT_BRANCH
    - git rev-parse HEAD
    - docker compose up -d --build
    - docker compose exec -T stbip php artisan db:seed --force
    - docker compose exec -T stbip php artisan config:clear
    - docker compose exec -T stbip php artisan optimize:clear
   # - docker compose exec -T stbip php artisan config:clear
   # - docker compose exec -T stbip php artisan optimize:clear
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      exists:
        - .gitlab-ci.yml
